# Generated by Django 3.2.9 on 2021-11-22 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_remove_registro_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total',
        ),
    ]
